/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   etools-loading-mixin.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {dedupingMixin} from '@polymer/polymer/lib/utils/mixin.js';

declare function internalLoadingMixin<T extends new (...args: any[]) => {}>(base: T): T & internalLoadingMixinConstructor;

interface internalLoadingMixinConstructor {
  new(...args: any[]): internalLoadingMixin;
}

export {internalLoadingMixinConstructor};

interface internalLoadingMixin {
  connectedCallback(): void;

  /**
   * This method will create an etools-loading absolute element
   * (loading element is appended to the body and it will cover entire screen)
   */
  createLoading(loadingMessage: any): Element|null;

  /**
   * Use this method to remove a loading element in the detached state of the element where loading is used
   */
  removeLoading(loadingElement: any): void;
  addMessageToQue(messages: any, source: any): any;
  removeMessageFromQue(messages: any, source: any): any;

  /**
   * Show loading when data is requested from server, or save is in progress...
   */
  handleLoading(event: any): void;
  clearLoadingQueue(event: any): void;
}

declare function LoadingMixin<T extends new (...args: any[]) => {}>(base: T): T & LoadingMixinConstructor;

interface LoadingMixinConstructor {
  new(...args: any[]): LoadingMixin;
}

export {LoadingMixinConstructor};

interface LoadingMixin {
}
